version: '0.1'
name: course_service
services:
  course_service:
    build: .
    ports:
      - '8080:8080'
    networks:
      - course_management_network
    command:
    depends_on:
      - course_db

  course_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'courseservice_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    networks:
      - course_management_network
    volumes:
      - my-course-db:/var/lib/mysql

volumes:
  my-course-db:

networks:
  course_management_network:
    driver: bridge
